version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  ApplicationStop:
    - location: scripts/appstop.sh
      timeout: 6000
      runas: ubuntu
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 6000      
